name: Entrega continua

on:
  workflow_call:
  
jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: Configurando credenciais AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Obtendo arquivo da tarefa
      run: aws ecs describe-task-definition --task-definition tarefa-api-go --query taskDefinition > task-definition.json
    
    - name: Copia do task-definition
      run: cp task-definition.json task-definition.json.old
    
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: go
        image: gabrielbelloni/go_ci:${{ github.run_number }}
        environment-variables: |
          HOST=${{ secrets.DB_HOST }}
          USER=${{ secrets.DB_USER }}
          PASSWORD=${{ secrets.DB_PASSWORD }}
          DBNAME=${{ secrets.DB_NAME }}
          DBPORT=${{ secrets.DB_PORT }}
          PORT=8000
          
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: api-go-service
        cluster: api-go
        wait-for-service-stability: true
