name: Kubernetes

on:
  workflow_call:
  
jobs:

  EKS:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configurando credenciais AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
        
    - run: git clone https://github.com/belloniz/curso-alura-infra-06
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    - run: terraform -chdir=curso-alura-infra-06/env/Homolog init
    
    # comando pra destruir a infra e nao gerar custos
    #- run: terraform -chdir=infra-ci-curso-alura-06/env/Homolog destroy -auto-approve
    #- run: return 1
    
    - run: terraform -chdir=curso-alura-infra-06/env/Homolog apply -auto-approve
    
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3
      
    - run: aws sts get-caller-identity
    
    - run: aws eks update-kubeconfig --region us-east-1 --name homolog2
    
    - run: kubectl get svc
