name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      DBPORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      run: docker-compose build
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go 
      
    - name: Configurando credenciais AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
        
    - run: git clone https://github.com/belloniz/curso-alura-infra-06
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    - run: terraform -chdir=curso-alura-infra-06/env/Homolog init
    
    # comando pra destruir a infra e nao gerar custos
    - run: terraform -chdir=infra-ci-curso-alura-06/env/Homolog destroy -auto-approve
    - run: return 1
      
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
    # Artifact name
        name: programa 
    # A file, directory or wildcard pattern that describes what to upload
        path: main
      
  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
  
  Deploy_EKS:
    needs: docker
    uses: ./.github/workflows/EKS.yml
    secrets: inherit
  
  #Deploy_ECS:
  #  needs: docker
  #  uses: ./.github/workflows/ECS.yml
  #  secrets: inherit
    
  #load-test:
  #  needs: docker
  #  if: ${{ github.ref_name == 'homolog' }}
  #  uses: ./.github/workflows/load-test.yml
  #  secrets: inherit
    
  #Deploy_EC2:
  #  needs: build
  #  uses: ./.github/workflows/EC2.yml
  #  secrets: inherit
